### ISSUE TITLE
Currently RPG Maker MZ games do not launch on Linux.

### ISSUE THREAD

**Issue by vickyorlo** [Orochimarufan/Kawariki#3]
See title. Attempting to run an MZ game results in the following traceback.
I did a bit of debugging with pdb and I think the template system for version jsons does not work correctly at the moment. The string mentioned comes from the "*templates" at distribution.py:143. The codebase is fairly complex so I couldn't figure out any more.

```
❯ python ./kawariki run /gamepath/Game.exe
[Kawariki] v2.0a0, python 3.12.7.final.0; run /gamepath/Game.exe
[Kawariki] Looks like RPGMaker MZ 1.4.0
[Kawariki] Kawariki Runtime Error:
[Kawariki]       Traceback (most recent call last):
[Kawariki]         File "/home/vic/bin/Kawariki/./kawariki", line 66, in <module>
[Kawariki]           sys.exit(main(app, sys.argv))
[Kawariki]                    ^^^^^^^^^^^^^^^^^^^
[Kawariki]         File "/home/vic/bin/Kawariki/lib/kawariki/main.py", line 245, in main
[Kawariki]           return runtime.run(game, args.game_args,
[Kawariki]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Kawariki]         File "/home/vic/bin/Kawariki/lib/kawariki/nwjs/runtime.py", line 810, in run
[Kawariki]           nwjs = self.select_and_download_nwjs(game, nwjs_name, sdk)
[Kawariki]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Kawariki]         File "/home/vic/bin/Kawariki/lib/kawariki/nwjs/runtime.py", line 575, in select_and_download_nwjs
[Kawariki]           nwjs = self.select_nwjs_version(game, nwjs_name, sdk)
[Kawariki]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Kawariki]         File "/home/vic/bin/Kawariki/lib/kawariki/nwjs/runtime.py", line 545, in select_nwjs_version
[Kawariki]           nwjs = self.get_nwjs_version(minver=(0, 13), sdk=sdk)
[Kawariki]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Kawariki]         File "/home/vic/bin/Kawariki/lib/kawariki/nwjs/runtime.py", line 494, in get_nwjs_version
[Kawariki]           if v := sorted([ver for ver in self.nwjs_versions
[Kawariki]                                          ^^^^^^^^^^^^^^^^^^
[Kawariki]         File "/usr/lib/python3.12/functools.py", line 993, in __get__
[Kawariki]           val = self.func(instance)
[Kawariki]                 ^^^^^^^^^^^^^^^^^^^
[Kawariki]         File "/home/vic/bin/Kawariki/lib/kawariki/nwjs/runtime.py", line 474, in nwjs_versions
[Kawariki]           return NWjs.load_json(self.base_path / "versions.json", self.nwjs_dist_path, self.app.platform)
[Kawariki]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Kawariki]         File "/home/vic/bin/Kawariki/lib/kawariki/distribution.py", line 254, in load_json
[Kawariki]           return cls.load_data(data, dist_path, platform)  # type: ignore
[Kawariki]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Kawariki]         File "/home/vic/bin/Kawariki/lib/kawariki/distribution.py", line 244, in load_data
[Kawariki]           for ver in cls.load_variants(cast(DI, i), dist_path, platform, platform_map, templates)]
[Kawariki]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Kawariki]         File "/home/vic/bin/Kawariki/lib/kawariki/nwjs/runtime.py", line 55, in <genexpr>
[Kawariki]           return (cls(info, dist_path, platform, platform_map, defaults) for info in infos)
[Kawariki]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Kawariki]         File "/home/vic/bin/Kawariki/lib/kawariki/distribution.py", line 148, in __init__
[Kawariki]           if platforms := infos.get('platforms'):
[Kawariki]                           ^^^^^^^^^^^^^^^^^^^^^^
[Kawariki]         File "/home/vic/bin/Kawariki/lib/kawariki/utils/interpolated_chain_map.py", line 71, in get
[Kawariki]           return self[key]
[Kawariki]                  ~~~~^^^^^
[Kawariki]         File "/home/vic/bin/Kawariki/lib/kawariki/utils/interpolated_chain_map.py", line 64, in __getitem__
[Kawariki]           value = self._getraw(key)
[Kawariki]                   ^^^^^^^^^^^^^^^^^
[Kawariki]         File "/home/vic/bin/Kawariki/lib/kawariki/utils/interpolated_chain_map.py", line 41, in _getraw
[Kawariki]           return mapping[key]
[Kawariki]                  ~~~~~~~^^^^^
[Kawariki]       TypeError: string indices must be integers, not 'str'
```

**Comment by Orochimarufan** [comment]
Ah sorry, some changes slipped through when committing that meant the NW.js distro handling wasn't properly adjusted for the core changes. That's what I get from running a dirty tree locally...

It should be fixed in 433d4c2ad1099efdb9b9020b47907f35d3355566. Thanks for the report

**Comment by vickyorlo** [comment]
Well, got nw running, but the game still doesn't launch... It opens an Electron window with the message:

```Your file couldn’t be accessed
It may have been moved, edited, or deleted.
ERR_FILE_NOT_FOUND
```

Here's the log:

```
❯ ./kawariki run "/gamepath/Game.exe"
[Kawariki] v2.0a0, python 3.12.7.final.0; run '/gamepath/Game.exe'
[Kawariki] Looks like RPGMaker MZ 1.4.0
[Kawariki] Selected NW.js version: NW.js v0.93.0 (linux-x64)
[Kawariki] Patching Greenworks at '/gamepath/greenworks.js'
[Kawariki] Created temporary directory:  /tmp/kawariki-xbve9pwe
[Kawariki] Running /home/vic/bin/Kawariki/dist/nwjs/nwjs-0.93.0-nosdk-linux-x64/nw . in /gamepath
[Kawariki] Executing [/home/vic/bin/Kawariki/overlayns-static -m 'bind,/tmp/kawariki-xbve9pwe/.vpc18es6,/gamepath' -m 'bind,/tmp/kawariki-xbve9pwe/packagec_5q3493.json,/gamepath/package.json' -- /home/vic/bin/Kawariki/dist/nwjs/nwjs-0.93.0-nosdk-linux-x64/nw .] in '/gamepath'
[1126/000639.684839:ERROR:elf_dynamic_array_reader.h(64)] tag not found
```

Also, a small nitpick, the required version of Python in README.md is too low. I think it should be 3.11+ now.

**Comment by Orochimarufan** [comment]
You're correct, the README is quite out of date. I need to get around to updating a good portion of it. It should be 3.10+ currently. I haven't felt like there was a lot of interest, so I've been prioritizing on making it run the games I play.

As for the game, that seems to be a game-specific issue. So I'd have to know more about the game you're trying to play to do anything about it. Unfortunately, the terminal output of NW.js is kind of useless once it launches successfully. You can try running with `KAWARIKI_SDK=1 KAWARIKI_NWJS_DEVTOOLS=1` to get more information. 
`KAWARIKI_NWJS_CIFS=1` may help if the game uses Node APIs for loading resources (As opposed to XHR, fetch or similar which are intercepted by default).

**Comment by vickyorlo** [comment]
I'm... sadly under a sort of an unofficial NDA, so I'd rather not mention the game, but I think the issue is related to greenworks integration/patching.
I tried an earlier version of the previous game that does not have greenworks, and it works perfectly.
I then went trying random RPG Maker MZ games on itch.io and Steam, and here's my results:
Two random MZ projects from itch.io, Gorgonia - A Gorgon's Tragedy Mario In Animatronic Horror, work fine.
Free Steam game on RPG Maker MZ, The Aquarium does not dance, but notably does not use greenworks, works fine.
The Coffin of Andy and Leyley, paid game, RPG Maker **MV** has greenworks, launches, but has a black screen and after a while the Kawariki "timed out" screen appears.
买个可乐饼吧！ - Buy a Croquette!, a free Steam RPG Maker **MV** game, uses greenworks, replicates my previous problem.

I might be wrong, but at least you can use that croquette game to test on your end.

**Comment by Orochimarufan** [comment]
You were correct, it was a greenworks patching problem. I was doing it in a pretty dumb way (hindsight is 20/20) that caused it to fail when greenworks is in the game's root folder (www is the root folder of MV games for all intents and purposes). I really wish kernel overlayfs would work with casefolding lowerdirs so I could get rid of these workarounds 😢
With that said, 3cef83e77f97498f4eecc56132a248bfa3556f2c should fix it.

There still seems to be a crashing problem with greenworks, but it's coming from the native library so I'm not sure what that's about.

I can recommend using SteamDB to find relevant games, it has much better filters and can show a file list without downloading a game (after selecting the relevant depot). E.g. https://steamdb.info/instantsearch/?refinementList%5Btechnologies%5D%5B0%5D=Engine.RPGMaker&refinementList%5Btechnologies%5D%5B1%5D=SDK.Greenworks&range%5Bprice_us%5D=%3A0

**Comment by Orochimarufan** [comment]
Did this resolve all issues with your game?

**Comment by vickyorlo** [comment]
Oops, sorry. Seems like everything works now, closing.
